name: israel_del_cargo_app
description: A Flutter application for IsraelDelCargo services.

# Version of the application
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # SQLite database operations
  sqflite: ^2.2.8
  path: ^1.8.3

  # Opening URLs (e.g., for WhatsApp)
  url_launcher: ^6.1.10

  # Storing data on the device
  shared_preferences: ^2.1.1

  # Image picker (for profile avatar)
  image_picker: ^0.8.7+4

  # Local authentication for Face ID
  local_auth: ^2.1.3

  # OpenStreetMap
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Assets (images, fonts, etc.)
  assets:
    - assets/images/logo.png
    