name: israel_del_cargo_app
description: A Flutter application for IsraelDelCargo services.

# Версия приложения
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Управление состоянием
  provider: ^6.0.5

  # Работа с базой данных SQLite
  sqflite: ^2.2.8
  path: ^1.8.3

  # Открытие URL (например, для WhatsApp)
  url_launcher: ^6.1.10

  # Хранение данных на устройстве
  shared_preferences: ^2.1.1

  # Выбор изображений (для аватара профиля)
  image_picker: ^0.8.7+4

  # Локальная аутентификация для Face ID
  local_auth: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Определение активов (изображений, шрифтов и т.д.)
  assets:
    - assets/images/logo.png
